### ISSUE TITLE
"self" o no "self", esa es la cuestión ...

### ISSUE THREAD

**Issue by tongilcoto** [applecodingacademy/StarWarsDemo-MoureDev-Masterclass#2]
https://github.com/applecodingacademy/StarWarsDemo-MoureDev-Masterclass/blob/787d857ca4a238575beacfaf2d9f832e7fe31c9d/StarWarsDemo/StarCardVM.swift#L19

Hola Brais y Julio!!
He estado siguiendo con mucha atención vuestra masterclass. Muchas gracias por el video

Sobre esta parte del "init" tengo una duda. Cual es la diferencia entre usar el "self" en "self.repository = " y no usarlo en  "cards = ". Lo más sorprendente para mi es que funciona .. cuando vi el video pensé que luego lo ibais a corregir, añadiendo el "self" al "cards", pero no 

muchas gracias de nuevo

**Comment by applecodingacademy** [comment]
Hola, Muy buena pregunta.

Swift es un lenguaje que permite la creación de variables con el mismo nombre dentro de ámbitos más profundos, y las sobrescribe. Por este motivo, cuando en el `init` recuperamos el valor de `repository` con: 

```swift
init(repository: DataRepository = Repository()) {
}
``` 

Lo que sucede es que dentro del ámbito de las llaves, `repository` es la que se ha recibido como parámetro en el `init` y no la propiedad de la clase que ha sido ocultada (sobrescrita). Por eso, para referenciar a la propiedad de la clase y no a la del parámetro, antecedemos `self.` lo que permite diferenciar a qué propiedad nos referimos. Sin embargo, como `cards` solo hay una, no es necesario ponerlo.

Espero haberte aclarado la duda.
Un saludo
